# test
language: go
before_install:
  - pushd $HOME
  - wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.6.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.6.zip
  - cd go_appengine
  - export GAE=$(pwd)
  - popd
install:
  - export GOHOME=$GAE
  - export PATH=$GAE:$PATH
  - which goapp
  - goapp env
script:
  - goapp test -v ./...
