application: innerhearthyoga
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /login/confirm.*
  script: _go_app
  login: required
- url: /login/admin.*
  script: _go_app
  login: admin
- url: /registration/admin.*
  script: _go_app
  login: required
- url: /registration.*
  script: _go_app
  login: required
- url: /task/.*
  script: _go_app
  login: admin
- url: /admin.*
  script: _go_app
  login: required
- url: /.*
  script: _go_app